const html5 = {
  h1h6 : 'All six leaves of Headings, with 1 being the most important on a page and 6 being the least. These elements are used to describe content sections on a page.',
  span : 'An inline section or block container, typically used for grouping styling elements',
  p : 'This foundational tag is used to organize paragraphs of text',
  br : 'Crates a line break useful to for writing blocks of text that need to be on different lines.',
  hr : 'Create a horizontal rule, a sectional break in an HTML page. Typically used to denote a change in topic or section of a page.',

  strong : 'Indicates STROG emphasis, displayed bold in most browsers',
  b: 'Another way to create bold text, it is more for drawing attention',
  em: 'The emphasis tags also are like they sound, emphasizing text',
  i : 'add italics to text, used to denote things like thoughts or names',
  cite : 'Tags used to cite or reference information, useful for quotes and statements in a document',
  pre : 'pre.formatted, monospace text laid out with whitespace',
  del : 'Helps denote a previously deleted section of text',
  ins : 'Represents a section of text thats been inserted into the document',
  blockquote : 'Reserved for long paragraphs of quotations often cited',
  q : 'These are used for shorter quotations',
  abbr : 'Abbreviation these help denote abbreviations, while also making the full form available',
  address : 'Displays the author´s contact information',
  dfn : 'Definition used to create an inline definition in the body text',
  code : 'Code text displays code snippets',
  sub : 'Subscript text a helpful way to subscript text',
  small : 'Small size text Historically used to simply reduce text size, in HTML5 it also refers to information that may no longer be valid',
  bdo : 'The bi-directional override tag will identify which should text should be read opposite from the preceding text',

  href: 'anchor text for hyperlink',
  mailto: 'A link used to pull up an outgoing message to a specific email addresses',
  tel: 'A link to make phone numbers clickable, especially useful for mobiles users',
  name: 'An anchor that´s useful for bringing users to specific document elements',
  tagname: 'An anchor link that brings users specifically to a div element',

  img: 'An image tag to include and display image files',
  map: 'Helps you tell users that is an interactive image with clickable areas',
  area: 'Specify the area of image map',
  src: "Exactly like it sounds. The URL of file of the image to display",
  alt: 'Alternative text that helps explain the image content to both search engines and users',
  height: 'Specify image height in pixels or percentages',
  width: 'Specify width in pixels or percentage',
  align: 'The alignment of the image (relative to other text elements on the page)',
  border: 'Explains the border thickness',
  vspace: 'Denote spacing on top or the bottom of image',
  hspace: 'Denote spacing on top or the bottom of image',
};

export default html5;
